version: '3'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raihan
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: golang
    volumes:
      - ./db_data/postgres:/var/lib/postgresql/data
    restart: on-failure:5